### ISSUE TITLE
`ClassNotFoundException: org.mariadb.jdbc.Driver` with `mesh-mariadb` docker image

### ISSUE THREAD

**Issue by nerbb-techmatrix** [gentics/mesh#1650]
Hi, I'm trying to use gentics mesh v3.0.2 in docker.

As described in the [Administration Guide](https://www.gentics.com/mesh/docs/administration-guide/) my docker compose file looks something like this

```
  mariadb:
    image: mariadb:11.6.2
    command: --transaction-isolation=READ-COMMITTED
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mesh
      MYSQL_USER: mesh
      MYSQL_PASSWORD: meshpassword
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb_data:/var/lib/mysql
    networks:
      - mesh-net

  mesh:
    image: gentics/mesh-mariadb:3.0.2
      # entrypoint: '/bin/sh -c "sleep  1000"'
    volumes:
      - ./mesh-uploads:/uploads
    ports:
      - '8080:8080'
    environment:
      MESH_DATABASE_ADDRESS: "mariadb:3306"
      MESH_JDBC_DATABASE_NAME: mesh
      MESH_JDBC_CONNECTION_USERNAME: "mesh"
      MESH_JDBC_CONNECTION_PASSWORD: "meshpassword"
      MESH_INITIAL_ADMIN_PASSWORD: "admin"
      MESH_INITIAL_ADMIN_PASSWORD_FORCE_RESET: "false"
      MESH_BINARY_DIR: "/uploads"
    networks:
      - mesh-net
```

However starting the server fails with this error

```
mesh-1  | 15:44:33.798 [] ERROR [main] [c.g.m.cli.MeshImpl] - FATAL: error on Mesh init
mesh-1  | java.lang.RuntimeException: Could not instantiate a database connector
mesh-1  |       at com.gentics.mesh.dagger.DatabaseConnectorModule.databaseConnector(DatabaseConnectorModule.java:66)
mesh-1  |       at com.gentics.mesh.dagger.DatabaseConnectorModule_DatabaseConnectorFactory.databaseConnector(DatabaseConnectorModule_DatabaseConnectorFactory.java:37)
mesh-1  |       at com.gentics.mesh.dagger.DatabaseConnectorModule_DatabaseConnectorFactory.get(DatabaseConnectorModule_DatabaseConnectorFactory.java:28)
mesh-1  |       at com.gentics.mesh.dagger.DatabaseConnectorModule_DatabaseConnectorFactory.get(DatabaseConnectorModule_DatabaseConnectorFactory.java:10)
...
mesh-1  | Caused by: java.lang.IllegalStateException: java.lang.ClassNotFoundException: org.mariadb.jdbc.Driver
mesh-1  |       at com.gentics.mesh.database.connector.AbstractDatabaseConnector.getJdbcDriverClass(AbstractDatabaseConnector.java:100)
mesh-1  |       at com.gentics.mesh.database.connector.AbstractDatabaseConnector.getConnectorDescription(AbstractDatabaseConnector.java:144)
mesh-1  |       at com.gentics.mesh.dagger.DatabaseConnectorModule.lambda$databaseConnector$3(DatabaseConnectorModule.java:62)
...
mesh-1  | Caused by: java.lang.ClassNotFoundException: org.mariadb.jdbc.Driver
mesh-1  |       at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
...
```

[This page](https://www.gentics.com/mesh/premium-features/premium-db/) mentions

> The connector for MariaDB is freely distributed at our Github Releases.

I assume that the `mesh-mariadb` image (which I am using) already has that connector, since there is a file present at `/mesh/database/mesh-connector.jar` inside the container, is that correct?

Any hints about what I might be doing wrong?

Thanks in advance for your help :)

PS: I've also posted this in your [Matrix Chat](https://matrix.to/#/!NoDwgCuqPFApCgppXV:gitter.im/$7HeTyc3sNw_BoFzZK7DIQSCCnd1ZnJ-CWNAFvK8kWJg?via=gitter.im&via=matrix.org)
