### ISSUE TITLE
[ENV] Make it possible to override all settings with environment variables

### ISSUE THREAD

**Issue by netwarex** [gentics/mesh#640]
## Gentics Mesh Version, operating system, or hardware.
- v0.29.4

## Operating System
- any

## JVM
- any

## Problem
Some Mesh settings can be overridden by environment variables, but not all of them, which can be useful in many scenarios (eg.: in Docker environment).

## Reproducer
[https://getmesh.io/docs/administration-guide/#_environment_variables](https://getmesh.io/docs/administration-guide/#_environment_variables)

## Expected behaviour and actual behaviour
I would recommend to use an enviroment variable pattern to override all settings keys, and use an exception for list for settings which should not be overridden (so these environment variables can be discarded).

Example:

mesh.yml:
```yaml
[...]
httpServer:
  port: 8080
  host: "0.0.0.0"
  corsAllowedOriginPattern: ""
  corsAllowCredentials: false
  enableCors: false
  ssl: false
  certPath: "config/cert.pem"
  keyPath: "config/key.pem"
cluster:
  enabled: false
  vertxPort: 0
storage:
  directory: "data/graphdb"
  backupDirectory: "data/backup"
  exportDirectory: "data/export"
[...]
```
Environment variable pattern:
```bash
MESH_LEVEL1_LEVEL2=VALUE
MESH_HTTPSERVER_PORT=8000
MESH_CLUSTER_ENABLED=FALSE
MESH_STORAGE_DIRECTORY="data/graphdb"
```
